---
- name: Configurar servidor web
  hosts: servers
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Iniciar el servicio Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copiar archivo HTML al directorio de Apache
      copy:
        src: /path/to/your/index.html
        dest: /var/www/html/index.html
